//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProject.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaKhuyenMai
    {
        public string MaKM { get; set; }
        public string TrangThai { get; set; }
        public Nullable<float> TiLe { get; set; }
    }
}
