//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyProject.Domain
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QLVanPhongEntities : DbContext
    {
        public QLVanPhongEntities()
            : base("name=QLVanPhongEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChiTietHoaDon> ChiTietHoaDons { get; set; }
        public virtual DbSet<ChiTietPhieu> ChiTietPhieux { get; set; }
        public virtual DbSet<DanhMucSP> DanhMucSPs { get; set; }
        public virtual DbSet<HoaDon> HoaDons { get; set; }
        public virtual DbSet<KhachHang> KhachHangs { get; set; }
        public virtual DbSet<Kho> Khoes { get; set; }
        public virtual DbSet<MaKhuyenMai> MaKhuyenMais { get; set; }
        public virtual DbSet<NguoiDung> NguoiDungs { get; set; }
        public virtual DbSet<NhaCungCap> NhaCungCaps { get; set; }
        public virtual DbSet<NhanVien> NhanViens { get; set; }
        public virtual DbSet<PhieuNhapXuat> PhieuNhapXuats { get; set; }
        public virtual DbSet<SanPham> SanPhams { get; set; }
    
        public virtual int CheckConnection()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CheckConnection");
        }
    
        public virtual int Delete_ChiTietHD(string maHD, string maSP)
        {
            var maHDParameter = maHD != null ?
                new ObjectParameter("MaHD", maHD) :
                new ObjectParameter("MaHD", typeof(string));
    
            var maSPParameter = maSP != null ?
                new ObjectParameter("MaSP", maSP) :
                new ObjectParameter("MaSP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Delete_ChiTietHD", maHDParameter, maSPParameter);
        }
    
        public virtual int Delete_ChiTietPhieu(string maPhieu, string maSP)
        {
            var maPhieuParameter = maPhieu != null ?
                new ObjectParameter("MaPhieu", maPhieu) :
                new ObjectParameter("MaPhieu", typeof(string));
    
            var maSPParameter = maSP != null ?
                new ObjectParameter("MaSP", maSP) :
                new ObjectParameter("MaSP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Delete_ChiTietPhieu", maPhieuParameter, maSPParameter);
        }
    
        public virtual int Delete_DanhMucSP(string maDM)
        {
            var maDMParameter = maDM != null ?
                new ObjectParameter("MaDM", maDM) :
                new ObjectParameter("MaDM", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Delete_DanhMucSP", maDMParameter);
        }
    
        public virtual int Delete_HoaDon(string maHD)
        {
            var maHDParameter = maHD != null ?
                new ObjectParameter("MaHD", maHD) :
                new ObjectParameter("MaHD", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Delete_HoaDon", maHDParameter);
        }
    
        public virtual int Delete_kho(string maSP, string maPhieu)
        {
            var maSPParameter = maSP != null ?
                new ObjectParameter("MaSP", maSP) :
                new ObjectParameter("MaSP", typeof(string));
    
            var maPhieuParameter = maPhieu != null ?
                new ObjectParameter("MaPhieu", maPhieu) :
                new ObjectParameter("MaPhieu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Delete_kho", maSPParameter, maPhieuParameter);
        }
    
        public virtual int Delete_MaKM(string maKM)
        {
            var maKMParameter = maKM != null ?
                new ObjectParameter("MaKM", maKM) :
                new ObjectParameter("MaKM", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Delete_MaKM", maKMParameter);
        }
    
        public virtual int Delete_NguoiDung(string iD)
        {
            var iDParameter = iD != null ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Delete_NguoiDung", iDParameter);
        }
    
        public virtual int Delete_NhaCungCap(string maNCC)
        {
            var maNCCParameter = maNCC != null ?
                new ObjectParameter("MaNCC", maNCC) :
                new ObjectParameter("MaNCC", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Delete_NhaCungCap", maNCCParameter);
        }
    
        public virtual int Delete_NhanVien(string manv)
        {
            var manvParameter = manv != null ?
                new ObjectParameter("Manv", manv) :
                new ObjectParameter("Manv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Delete_NhanVien", manvParameter);
        }
    
        public virtual int Delete_PhieuNhapXuat(string maPhieu)
        {
            var maPhieuParameter = maPhieu != null ?
                new ObjectParameter("MaPhieu", maPhieu) :
                new ObjectParameter("MaPhieu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Delete_PhieuNhapXuat", maPhieuParameter);
        }
    
        public virtual int Delete_SanPham(string maSP)
        {
            var maSPParameter = maSP != null ?
                new ObjectParameter("MaSP", maSP) :
                new ObjectParameter("MaSP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Delete_SanPham", maSPParameter);
        }
    
        public virtual int DeleteAll_ChiTietHD(string maHD)
        {
            var maHDParameter = maHD != null ?
                new ObjectParameter("MaHD", maHD) :
                new ObjectParameter("MaHD", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteAll_ChiTietHD", maHDParameter);
        }
    
        public virtual int DeleteAll_ChiTietPhieu(string maPhieu)
        {
            var maPhieuParameter = maPhieu != null ?
                new ObjectParameter("MaPhieu", maPhieu) :
                new ObjectParameter("MaPhieu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteAll_ChiTietPhieu", maPhieuParameter);
        }
    
        public virtual int DeleteKhachHang(string maKH)
        {
            var maKHParameter = maKH != null ?
                new ObjectParameter("MaKH", maKH) :
                new ObjectParameter("MaKH", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteKhachHang", maKHParameter);
        }
    
        public virtual int InSert_ChiTietHD(string maHD, string maSP, Nullable<decimal> donGia, Nullable<int> soLuong)
        {
            var maHDParameter = maHD != null ?
                new ObjectParameter("MaHD", maHD) :
                new ObjectParameter("MaHD", typeof(string));
    
            var maSPParameter = maSP != null ?
                new ObjectParameter("MaSP", maSP) :
                new ObjectParameter("MaSP", typeof(string));
    
            var donGiaParameter = donGia.HasValue ?
                new ObjectParameter("DonGia", donGia) :
                new ObjectParameter("DonGia", typeof(decimal));
    
            var soLuongParameter = soLuong.HasValue ?
                new ObjectParameter("SoLuong", soLuong) :
                new ObjectParameter("SoLuong", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InSert_ChiTietHD", maHDParameter, maSPParameter, donGiaParameter, soLuongParameter);
        }
    
        public virtual int Insert_ChiTietPhieu(string maSP, string maPhieu, Nullable<decimal> donGia, Nullable<int> soLuong)
        {
            var maSPParameter = maSP != null ?
                new ObjectParameter("MaSP", maSP) :
                new ObjectParameter("MaSP", typeof(string));
    
            var maPhieuParameter = maPhieu != null ?
                new ObjectParameter("MaPhieu", maPhieu) :
                new ObjectParameter("MaPhieu", typeof(string));
    
            var donGiaParameter = donGia.HasValue ?
                new ObjectParameter("DonGia", donGia) :
                new ObjectParameter("DonGia", typeof(decimal));
    
            var soLuongParameter = soLuong.HasValue ?
                new ObjectParameter("SoLuong", soLuong) :
                new ObjectParameter("SoLuong", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Insert_ChiTietPhieu", maSPParameter, maPhieuParameter, donGiaParameter, soLuongParameter);
        }
    
        public virtual int InSert_DanhMucSP(string maDM, string tenDM, Nullable<int> soLuong)
        {
            var maDMParameter = maDM != null ?
                new ObjectParameter("MaDM", maDM) :
                new ObjectParameter("MaDM", typeof(string));
    
            var tenDMParameter = tenDM != null ?
                new ObjectParameter("TenDM", tenDM) :
                new ObjectParameter("TenDM", typeof(string));
    
            var soLuongParameter = soLuong.HasValue ?
                new ObjectParameter("SoLuong", soLuong) :
                new ObjectParameter("SoLuong", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InSert_DanhMucSP", maDMParameter, tenDMParameter, soLuongParameter);
        }
    
        public virtual int InSert_HoaDon(string maHD, Nullable<System.DateTime> ngayLap, string maNV, string maKH, Nullable<decimal> tongTien, string trangThai)
        {
            var maHDParameter = maHD != null ?
                new ObjectParameter("MaHD", maHD) :
                new ObjectParameter("MaHD", typeof(string));
    
            var ngayLapParameter = ngayLap.HasValue ?
                new ObjectParameter("NgayLap", ngayLap) :
                new ObjectParameter("NgayLap", typeof(System.DateTime));
    
            var maNVParameter = maNV != null ?
                new ObjectParameter("MaNV", maNV) :
                new ObjectParameter("MaNV", typeof(string));
    
            var maKHParameter = maKH != null ?
                new ObjectParameter("MaKH", maKH) :
                new ObjectParameter("MaKH", typeof(string));
    
            var tongTienParameter = tongTien.HasValue ?
                new ObjectParameter("TongTien", tongTien) :
                new ObjectParameter("TongTien", typeof(decimal));
    
            var trangThaiParameter = trangThai != null ?
                new ObjectParameter("TrangThai", trangThai) :
                new ObjectParameter("TrangThai", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InSert_HoaDon", maHDParameter, ngayLapParameter, maNVParameter, maKHParameter, tongTienParameter, trangThaiParameter);
        }
    
        public virtual int InSert_KhachHang(string maKH, string ten, string diaChi, string sdt)
        {
            var maKHParameter = maKH != null ?
                new ObjectParameter("MaKH", maKH) :
                new ObjectParameter("MaKH", typeof(string));
    
            var tenParameter = ten != null ?
                new ObjectParameter("Ten", ten) :
                new ObjectParameter("Ten", typeof(string));
    
            var diaChiParameter = diaChi != null ?
                new ObjectParameter("DiaChi", diaChi) :
                new ObjectParameter("DiaChi", typeof(string));
    
            var sdtParameter = sdt != null ?
                new ObjectParameter("Sdt", sdt) :
                new ObjectParameter("Sdt", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InSert_KhachHang", maKHParameter, tenParameter, diaChiParameter, sdtParameter);
        }
    
        public virtual int Insert_Kho(string maSP, string maPhieu, Nullable<int> soLuong, Nullable<System.DateTime> ngayLap, Nullable<System.DateTime> ngayXuat)
        {
            var maSPParameter = maSP != null ?
                new ObjectParameter("MaSP", maSP) :
                new ObjectParameter("MaSP", typeof(string));
    
            var maPhieuParameter = maPhieu != null ?
                new ObjectParameter("MaPhieu", maPhieu) :
                new ObjectParameter("MaPhieu", typeof(string));
    
            var soLuongParameter = soLuong.HasValue ?
                new ObjectParameter("SoLuong", soLuong) :
                new ObjectParameter("SoLuong", typeof(int));
    
            var ngayLapParameter = ngayLap.HasValue ?
                new ObjectParameter("NgayLap", ngayLap) :
                new ObjectParameter("NgayLap", typeof(System.DateTime));
    
            var ngayXuatParameter = ngayXuat.HasValue ?
                new ObjectParameter("NgayXuat", ngayXuat) :
                new ObjectParameter("NgayXuat", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Insert_Kho", maSPParameter, maPhieuParameter, soLuongParameter, ngayLapParameter, ngayXuatParameter);
        }
    
        public virtual int Insert_MaKhuyenMai(string maKM, string trangThai, Nullable<float> tiLe)
        {
            var maKMParameter = maKM != null ?
                new ObjectParameter("MaKM", maKM) :
                new ObjectParameter("MaKM", typeof(string));
    
            var trangThaiParameter = trangThai != null ?
                new ObjectParameter("TrangThai", trangThai) :
                new ObjectParameter("TrangThai", typeof(string));
    
            var tiLeParameter = tiLe.HasValue ?
                new ObjectParameter("TiLe", tiLe) :
                new ObjectParameter("TiLe", typeof(float));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Insert_MaKhuyenMai", maKMParameter, trangThaiParameter, tiLeParameter);
        }
    
        public virtual int Insert_NguoiDung(string iD, string pass, string mail, string maNV)
        {
            var iDParameter = iD != null ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(string));
    
            var passParameter = pass != null ?
                new ObjectParameter("Pass", pass) :
                new ObjectParameter("Pass", typeof(string));
    
            var mailParameter = mail != null ?
                new ObjectParameter("Mail", mail) :
                new ObjectParameter("Mail", typeof(string));
    
            var maNVParameter = maNV != null ?
                new ObjectParameter("MaNV", maNV) :
                new ObjectParameter("MaNV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Insert_NguoiDung", iDParameter, passParameter, mailParameter, maNVParameter);
        }
    
        public virtual int Insert_NhaCungCap(string maNCC, string ten, string diachi, string sdt)
        {
            var maNCCParameter = maNCC != null ?
                new ObjectParameter("MaNCC", maNCC) :
                new ObjectParameter("MaNCC", typeof(string));
    
            var tenParameter = ten != null ?
                new ObjectParameter("Ten", ten) :
                new ObjectParameter("Ten", typeof(string));
    
            var diachiParameter = diachi != null ?
                new ObjectParameter("Diachi", diachi) :
                new ObjectParameter("Diachi", typeof(string));
    
            var sdtParameter = sdt != null ?
                new ObjectParameter("sdt", sdt) :
                new ObjectParameter("sdt", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Insert_NhaCungCap", maNCCParameter, tenParameter, diachiParameter, sdtParameter);
        }
    
        public virtual int Insert_NhanVien(string manv, string ten, string diachi, string sdt, string chucVu, Nullable<int> luong)
        {
            var manvParameter = manv != null ?
                new ObjectParameter("Manv", manv) :
                new ObjectParameter("Manv", typeof(string));
    
            var tenParameter = ten != null ?
                new ObjectParameter("Ten", ten) :
                new ObjectParameter("Ten", typeof(string));
    
            var diachiParameter = diachi != null ?
                new ObjectParameter("Diachi", diachi) :
                new ObjectParameter("Diachi", typeof(string));
    
            var sdtParameter = sdt != null ?
                new ObjectParameter("sdt", sdt) :
                new ObjectParameter("sdt", typeof(string));
    
            var chucVuParameter = chucVu != null ?
                new ObjectParameter("ChucVu", chucVu) :
                new ObjectParameter("ChucVu", typeof(string));
    
            var luongParameter = luong.HasValue ?
                new ObjectParameter("Luong", luong) :
                new ObjectParameter("Luong", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Insert_NhanVien", manvParameter, tenParameter, diachiParameter, sdtParameter, chucVuParameter, luongParameter);
        }
    
        public virtual int Insert_PhieuNhapXuat(string maPhieu, string maNV, Nullable<decimal> tongtien, Nullable<System.DateTime> ngayLap, string trangThai)
        {
            var maPhieuParameter = maPhieu != null ?
                new ObjectParameter("MaPhieu", maPhieu) :
                new ObjectParameter("MaPhieu", typeof(string));
    
            var maNVParameter = maNV != null ?
                new ObjectParameter("MaNV", maNV) :
                new ObjectParameter("MaNV", typeof(string));
    
            var tongtienParameter = tongtien.HasValue ?
                new ObjectParameter("Tongtien", tongtien) :
                new ObjectParameter("Tongtien", typeof(decimal));
    
            var ngayLapParameter = ngayLap.HasValue ?
                new ObjectParameter("NgayLap", ngayLap) :
                new ObjectParameter("NgayLap", typeof(System.DateTime));
    
            var trangThaiParameter = trangThai != null ?
                new ObjectParameter("TrangThai", trangThai) :
                new ObjectParameter("TrangThai", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Insert_PhieuNhapXuat", maPhieuParameter, maNVParameter, tongtienParameter, ngayLapParameter, trangThaiParameter);
        }
    
        public virtual int Insert_SanPham(string maSP, string maNCC, string maDM, string tenSP, Nullable<decimal> donGia, Nullable<int> soLuong, string xuatXu, Nullable<double> trongLuong, Nullable<double> kichThuoc, string donVi)
        {
            var maSPParameter = maSP != null ?
                new ObjectParameter("MaSP", maSP) :
                new ObjectParameter("MaSP", typeof(string));
    
            var maNCCParameter = maNCC != null ?
                new ObjectParameter("MaNCC", maNCC) :
                new ObjectParameter("MaNCC", typeof(string));
    
            var maDMParameter = maDM != null ?
                new ObjectParameter("MaDM", maDM) :
                new ObjectParameter("MaDM", typeof(string));
    
            var tenSPParameter = tenSP != null ?
                new ObjectParameter("TenSP", tenSP) :
                new ObjectParameter("TenSP", typeof(string));
    
            var donGiaParameter = donGia.HasValue ?
                new ObjectParameter("DonGia", donGia) :
                new ObjectParameter("DonGia", typeof(decimal));
    
            var soLuongParameter = soLuong.HasValue ?
                new ObjectParameter("SoLuong", soLuong) :
                new ObjectParameter("SoLuong", typeof(int));
    
            var xuatXuParameter = xuatXu != null ?
                new ObjectParameter("XuatXu", xuatXu) :
                new ObjectParameter("XuatXu", typeof(string));
    
            var trongLuongParameter = trongLuong.HasValue ?
                new ObjectParameter("TrongLuong", trongLuong) :
                new ObjectParameter("TrongLuong", typeof(double));
    
            var kichThuocParameter = kichThuoc.HasValue ?
                new ObjectParameter("KichThuoc", kichThuoc) :
                new ObjectParameter("KichThuoc", typeof(double));
    
            var donViParameter = donVi != null ?
                new ObjectParameter("DonVi", donVi) :
                new ObjectParameter("DonVi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Insert_SanPham", maSPParameter, maNCCParameter, maDMParameter, tenSPParameter, donGiaParameter, soLuongParameter, xuatXuParameter, trongLuongParameter, kichThuocParameter, donViParameter);
        }
    
        public virtual int ThanhToan(Nullable<int> soluong, string masp)
        {
            var soluongParameter = soluong.HasValue ?
                new ObjectParameter("soluong", soluong) :
                new ObjectParameter("soluong", typeof(int));
    
            var maspParameter = masp != null ?
                new ObjectParameter("masp", masp) :
                new ObjectParameter("masp", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ThanhToan", soluongParameter, maspParameter);
        }
    
        public virtual int Update_ChiTietHD(string maHD, string maSP, Nullable<decimal> donGia, Nullable<int> soLuong)
        {
            var maHDParameter = maHD != null ?
                new ObjectParameter("MaHD", maHD) :
                new ObjectParameter("MaHD", typeof(string));
    
            var maSPParameter = maSP != null ?
                new ObjectParameter("MaSP", maSP) :
                new ObjectParameter("MaSP", typeof(string));
    
            var donGiaParameter = donGia.HasValue ?
                new ObjectParameter("DonGia", donGia) :
                new ObjectParameter("DonGia", typeof(decimal));
    
            var soLuongParameter = soLuong.HasValue ?
                new ObjectParameter("SoLuong", soLuong) :
                new ObjectParameter("SoLuong", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Update_ChiTietHD", maHDParameter, maSPParameter, donGiaParameter, soLuongParameter);
        }
    
        public virtual int Update_ChiTietPhieu(string maSP, string maPhieu, Nullable<decimal> donGia, Nullable<int> soLuong)
        {
            var maSPParameter = maSP != null ?
                new ObjectParameter("MaSP", maSP) :
                new ObjectParameter("MaSP", typeof(string));
    
            var maPhieuParameter = maPhieu != null ?
                new ObjectParameter("MaPhieu", maPhieu) :
                new ObjectParameter("MaPhieu", typeof(string));
    
            var donGiaParameter = donGia.HasValue ?
                new ObjectParameter("DonGia", donGia) :
                new ObjectParameter("DonGia", typeof(decimal));
    
            var soLuongParameter = soLuong.HasValue ?
                new ObjectParameter("SoLuong", soLuong) :
                new ObjectParameter("SoLuong", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Update_ChiTietPhieu", maSPParameter, maPhieuParameter, donGiaParameter, soLuongParameter);
        }
    
        public virtual int Update_DanhMucSP(string maDM, string tenDM, Nullable<int> soLuong)
        {
            var maDMParameter = maDM != null ?
                new ObjectParameter("MaDM", maDM) :
                new ObjectParameter("MaDM", typeof(string));
    
            var tenDMParameter = tenDM != null ?
                new ObjectParameter("TenDM", tenDM) :
                new ObjectParameter("TenDM", typeof(string));
    
            var soLuongParameter = soLuong.HasValue ?
                new ObjectParameter("SoLuong", soLuong) :
                new ObjectParameter("SoLuong", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Update_DanhMucSP", maDMParameter, tenDMParameter, soLuongParameter);
        }
    
        public virtual int Update_HoaDon(string maHD, Nullable<System.DateTime> ngayLap, string maNV, string maKH, Nullable<decimal> tongTien, string trangThai)
        {
            var maHDParameter = maHD != null ?
                new ObjectParameter("MaHD", maHD) :
                new ObjectParameter("MaHD", typeof(string));
    
            var ngayLapParameter = ngayLap.HasValue ?
                new ObjectParameter("NgayLap", ngayLap) :
                new ObjectParameter("NgayLap", typeof(System.DateTime));
    
            var maNVParameter = maNV != null ?
                new ObjectParameter("MaNV", maNV) :
                new ObjectParameter("MaNV", typeof(string));
    
            var maKHParameter = maKH != null ?
                new ObjectParameter("MaKH", maKH) :
                new ObjectParameter("MaKH", typeof(string));
    
            var tongTienParameter = tongTien.HasValue ?
                new ObjectParameter("TongTien", tongTien) :
                new ObjectParameter("TongTien", typeof(decimal));
    
            var trangThaiParameter = trangThai != null ?
                new ObjectParameter("TrangThai", trangThai) :
                new ObjectParameter("TrangThai", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Update_HoaDon", maHDParameter, ngayLapParameter, maNVParameter, maKHParameter, tongTienParameter, trangThaiParameter);
        }
    
        public virtual int Update_KhachHang(string maKH, string ten, string diaChi, string sdt)
        {
            var maKHParameter = maKH != null ?
                new ObjectParameter("MaKH", maKH) :
                new ObjectParameter("MaKH", typeof(string));
    
            var tenParameter = ten != null ?
                new ObjectParameter("Ten", ten) :
                new ObjectParameter("Ten", typeof(string));
    
            var diaChiParameter = diaChi != null ?
                new ObjectParameter("DiaChi", diaChi) :
                new ObjectParameter("DiaChi", typeof(string));
    
            var sdtParameter = sdt != null ?
                new ObjectParameter("Sdt", sdt) :
                new ObjectParameter("Sdt", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Update_KhachHang", maKHParameter, tenParameter, diaChiParameter, sdtParameter);
        }
    
        public virtual int Update_kho(string maSP, string maPhieu, Nullable<int> soLuong, Nullable<System.DateTime> ngayLap, Nullable<System.DateTime> ngayXuat)
        {
            var maSPParameter = maSP != null ?
                new ObjectParameter("MaSP", maSP) :
                new ObjectParameter("MaSP", typeof(string));
    
            var maPhieuParameter = maPhieu != null ?
                new ObjectParameter("MaPhieu", maPhieu) :
                new ObjectParameter("MaPhieu", typeof(string));
    
            var soLuongParameter = soLuong.HasValue ?
                new ObjectParameter("SoLuong", soLuong) :
                new ObjectParameter("SoLuong", typeof(int));
    
            var ngayLapParameter = ngayLap.HasValue ?
                new ObjectParameter("NgayLap", ngayLap) :
                new ObjectParameter("NgayLap", typeof(System.DateTime));
    
            var ngayXuatParameter = ngayXuat.HasValue ?
                new ObjectParameter("NgayXuat", ngayXuat) :
                new ObjectParameter("NgayXuat", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Update_kho", maSPParameter, maPhieuParameter, soLuongParameter, ngayLapParameter, ngayXuatParameter);
        }
    
        public virtual int Update_MaKhuyenMai(string maKM, string trangThai, Nullable<float> tiLe)
        {
            var maKMParameter = maKM != null ?
                new ObjectParameter("MaKM", maKM) :
                new ObjectParameter("MaKM", typeof(string));
    
            var trangThaiParameter = trangThai != null ?
                new ObjectParameter("TrangThai", trangThai) :
                new ObjectParameter("TrangThai", typeof(string));
    
            var tiLeParameter = tiLe.HasValue ?
                new ObjectParameter("TiLe", tiLe) :
                new ObjectParameter("TiLe", typeof(float));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Update_MaKhuyenMai", maKMParameter, trangThaiParameter, tiLeParameter);
        }
    
        public virtual int Update_NguoiDung(string iD, string pass, string mail, string maNV)
        {
            var iDParameter = iD != null ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(string));
    
            var passParameter = pass != null ?
                new ObjectParameter("Pass", pass) :
                new ObjectParameter("Pass", typeof(string));
    
            var mailParameter = mail != null ?
                new ObjectParameter("Mail", mail) :
                new ObjectParameter("Mail", typeof(string));
    
            var maNVParameter = maNV != null ?
                new ObjectParameter("MaNV", maNV) :
                new ObjectParameter("MaNV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Update_NguoiDung", iDParameter, passParameter, mailParameter, maNVParameter);
        }
    
        public virtual int Update_NhaCungCap(string maNCC, string ten, string diachi, string sdt)
        {
            var maNCCParameter = maNCC != null ?
                new ObjectParameter("MaNCC", maNCC) :
                new ObjectParameter("MaNCC", typeof(string));
    
            var tenParameter = ten != null ?
                new ObjectParameter("Ten", ten) :
                new ObjectParameter("Ten", typeof(string));
    
            var diachiParameter = diachi != null ?
                new ObjectParameter("Diachi", diachi) :
                new ObjectParameter("Diachi", typeof(string));
    
            var sdtParameter = sdt != null ?
                new ObjectParameter("sdt", sdt) :
                new ObjectParameter("sdt", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Update_NhaCungCap", maNCCParameter, tenParameter, diachiParameter, sdtParameter);
        }
    
        public virtual int Update_NhanVien(string manv, string ten, string diachi, string sdt, string chucVu, Nullable<int> luong)
        {
            var manvParameter = manv != null ?
                new ObjectParameter("Manv", manv) :
                new ObjectParameter("Manv", typeof(string));
    
            var tenParameter = ten != null ?
                new ObjectParameter("Ten", ten) :
                new ObjectParameter("Ten", typeof(string));
    
            var diachiParameter = diachi != null ?
                new ObjectParameter("Diachi", diachi) :
                new ObjectParameter("Diachi", typeof(string));
    
            var sdtParameter = sdt != null ?
                new ObjectParameter("sdt", sdt) :
                new ObjectParameter("sdt", typeof(string));
    
            var chucVuParameter = chucVu != null ?
                new ObjectParameter("ChucVu", chucVu) :
                new ObjectParameter("ChucVu", typeof(string));
    
            var luongParameter = luong.HasValue ?
                new ObjectParameter("Luong", luong) :
                new ObjectParameter("Luong", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Update_NhanVien", manvParameter, tenParameter, diachiParameter, sdtParameter, chucVuParameter, luongParameter);
        }
    
        public virtual int Update_PhieuNhapXuat(string maPhieu, string maNV, Nullable<decimal> tongTien, Nullable<System.DateTime> ngayLap, string trangThai)
        {
            var maPhieuParameter = maPhieu != null ?
                new ObjectParameter("MaPhieu", maPhieu) :
                new ObjectParameter("MaPhieu", typeof(string));
    
            var maNVParameter = maNV != null ?
                new ObjectParameter("MaNV", maNV) :
                new ObjectParameter("MaNV", typeof(string));
    
            var tongTienParameter = tongTien.HasValue ?
                new ObjectParameter("TongTien", tongTien) :
                new ObjectParameter("TongTien", typeof(decimal));
    
            var ngayLapParameter = ngayLap.HasValue ?
                new ObjectParameter("NgayLap", ngayLap) :
                new ObjectParameter("NgayLap", typeof(System.DateTime));
    
            var trangThaiParameter = trangThai != null ?
                new ObjectParameter("TrangThai", trangThai) :
                new ObjectParameter("TrangThai", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Update_PhieuNhapXuat", maPhieuParameter, maNVParameter, tongTienParameter, ngayLapParameter, trangThaiParameter);
        }
    
        public virtual int Update_SanPham(string maSP, string maNCC, string maDM, string tenSP, Nullable<decimal> donGia, Nullable<int> soLuong, string xuatXu, Nullable<double> trongLuong, Nullable<double> kichThuoc, string donVi)
        {
            var maSPParameter = maSP != null ?
                new ObjectParameter("MaSP", maSP) :
                new ObjectParameter("MaSP", typeof(string));
    
            var maNCCParameter = maNCC != null ?
                new ObjectParameter("MaNCC", maNCC) :
                new ObjectParameter("MaNCC", typeof(string));
    
            var maDMParameter = maDM != null ?
                new ObjectParameter("MaDM", maDM) :
                new ObjectParameter("MaDM", typeof(string));
    
            var tenSPParameter = tenSP != null ?
                new ObjectParameter("TenSP", tenSP) :
                new ObjectParameter("TenSP", typeof(string));
    
            var donGiaParameter = donGia.HasValue ?
                new ObjectParameter("DonGia", donGia) :
                new ObjectParameter("DonGia", typeof(decimal));
    
            var soLuongParameter = soLuong.HasValue ?
                new ObjectParameter("SoLuong", soLuong) :
                new ObjectParameter("SoLuong", typeof(int));
    
            var xuatXuParameter = xuatXu != null ?
                new ObjectParameter("XuatXu", xuatXu) :
                new ObjectParameter("XuatXu", typeof(string));
    
            var trongLuongParameter = trongLuong.HasValue ?
                new ObjectParameter("TrongLuong", trongLuong) :
                new ObjectParameter("TrongLuong", typeof(double));
    
            var kichThuocParameter = kichThuoc.HasValue ?
                new ObjectParameter("KichThuoc", kichThuoc) :
                new ObjectParameter("KichThuoc", typeof(double));
    
            var donViParameter = donVi != null ?
                new ObjectParameter("DonVi", donVi) :
                new ObjectParameter("DonVi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Update_SanPham", maSPParameter, maNCCParameter, maDMParameter, tenSPParameter, donGiaParameter, soLuongParameter, xuatXuParameter, trongLuongParameter, kichThuocParameter, donViParameter);
        }
    
        public virtual int UpdateLuong(string maNV)
        {
            var maNVParameter = maNV != null ?
                new ObjectParameter("MaNV", maNV) :
                new ObjectParameter("MaNV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateLuong", maNVParameter);
        }
    }
}
